//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM
{
    using System;
    using System.Collections.Generic;
    
    public partial class statistika
    {
        public string IDstatistika { get; set; }
        public Nullable<System.DateTime> mesec { get; set; }
        public Nullable<System.DateTime> godina { get; set; }
        public Nullable<double> prihod { get; set; }
        public int IDrezultat { get; set; }
    
        public virtual rezultati rezultati { get; set; }
    }
}
